// Contact Related Types
export const SET_CONTACT_PERMISSION_STATUS_SUCCESS =
  "SET_CONTACT_PERMISSION_STATUS_SUCCESS";
export const SET_CONTACT_PERMISSION_STATUS = "SET_CONTACT_PERMISSION_STATUS";
export const SET_SELECTED_CONTACT = "SET_SELECTED_CONTACT";
export const SET_SELECTED_CONTACT_SUCCESS = "SET_SELECTED_CONTACT_SUCCESS";
